Assignment4: berry_max_assn4.o berry_Zombie.o 
	g++  -g -Wall berry_max_assn4.cpp berry_Zombie.cpp -o Assignment4

berry_max_assn4.o: berry_max_assn4.cpp berry_max_list.h
	g++ -g -Wall -c berry_max_assn4.cpp

berry_Zombie.o: berry_Zombie.cpp berry_Zombie.h
	g++ -g -Wall -c berry_Zombie.cpp


clean: 
	rm *.o Assignment4